import assert from 'node:assert/strict';
import { connectionStatus } from '../lib/mcp/connection-status';
import { pointBreakdown } from '../lib/goals/point-breakdown';
import { generateKeyPairSync, sign } from 'node:crypto';
import { verifyConnectionReport } from '../lib/mcp/connection-auth';

const now = Date.parse('2026-09-26T12:00:00Z');
const keys = generateKeyPairSync('ed25519');
const key = keys.publicKey.export({ type: 'spki', format: 'pem' }).toString();
const body = JSON.stringify({ event: 'review-success', at: new Date(now).toISOString() });
const signature = sign(null, Buffer.from(body), keys.privateKey).toString('base64');
assert.equal(verifyConnectionReport(body, signature, now, key)?.lastSuccessfulReviewAt, new Date(now).toISOString());
assert.equal(verifyConnectionReport(body.replace('success', 'error'), signature, now, key), null);
assert.equal(verifyConnectionReport(body, signature, now + 61000, key), null);
assert.equal(verifyConnectionReport(body, '', now, key), null);
assert.equal(connectionStatus({}, now).state, 'Offline');
assert.equal(connectionStatus({ heartbeatAt: new Date(now - 91000).toISOString() }, now).state, 'Offline');
assert.equal(connectionStatus({ heartbeatAt: new Date(now).toISOString() }, now).state, 'Connected');
assert.equal(connectionStatus({ heartbeatAt: new Date(now).toISOString(), lastReviewErrorAt: new Date(now).toISOString() }, now).state, 'Retrying');
assert.equal(connectionStatus({ heartbeatAt: new Date(now).toISOString(), lastReviewErrorAt: new Date(now - 10000).toISOString(), lastSuccessfulReviewAt: new Date(now).toISOString() }, now).state, 'Connected');
const event = (id: string, kind: string, taskText: string, points: number) => ({ id, kind, taskText, points, scope: 'today', createdAt: `2026-09-26T0${id}:00:00Z` });
const events = [event('1', 'completion', 'Gym', 5), event('2', 'completion', 'Gym', 5), event('3', 'undo', 'Gym', 5), event('4', 'completion', 'Task', 5), event('5', 'undo', 'Task', 5), event('6', 'focus-session', 'Task', 10), event('7', 'completion', 'Zero', 0)];
const result = pointBreakdown(events.reverse(), '2026-09-26', text => text === 'Gym' ? 'GYM' : null, e => e.points);
assert.equal(result.total, 0);
assert.equal(result.rows.reduce((sum, row) => sum + row.delta, 0), result.total);
assert.equal(result.rows.find(row => row.id === '4')?.delta, 5);
assert.equal(result.rows.find(row => row.id === '5')?.delta, -5);
assert.equal(result.rows.find(row => row.id === '6')?.delta, 0);
assert.equal(pointBreakdown(events, '2026-09-25', () => null, e => e.points).total, 0);
console.log('Connection freshness, review failure/recovery, chronological point contributions, zero points, deduplication, undo and time-only events passed.');
